import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import "./globals.css";

// compoents
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <Navbar />
        <div className="p-10 min-h-[calc(100vh-80px-150px)]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
